### PR TITLE
Logo

### PR DESCRIPTION
**Pull request by milenapribic**
Hi @chrisdhanaraj, running into some errors when trying to push up a static image for Logo. Can you please look this over? Thanks!

### CODE REVIEW

**Comment by milenapribic** [comment]
Hi @chrisdhanaraj logo is ready for you to look at, thx.

**Comment by milenapribic** [comment]
Added the Link component @chrisdhanaraj

**Comment by chrisdhanaraj** [comment]
:+1:

**Comment by chrisdhanaraj** [comment]
We might have to rethink how we do svg's though

**Pull request merged**
